import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/Header";
import "./globals.css";
import Sidebar from "../components/LeftSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
 <Sidebar />
        <div
        className={` ml-[86px] w-auto`}
      >
       
        <Header />
        <main
          className="xl:px-18  lg:px-4  mx-auto px-4 pt-[62px]"
             
        >
          {children}
        </main>
      </div>

      
      </body>
    </html>
  );
}
